export const emojiData = {
  recent: [],
  smileys: [
    { id: 'smile', char: '😊', desc: '羞涩微笑' },
    { id: 'laughing', char: '😆', desc: '大笑' },
    { id: 'wink', char: '😉', desc: '眨眼' },
    { id: 'innocent', char: '😇', desc: '微笑天使' },
    { id: 'heart_eyes', char: '😍', desc: '花痴' },
    { id: 'kissing', char: '😗', desc: '亲亲' },
    { id: 'kissing_smiling_eyes', char: '😙', desc: '微笑亲亲' },
    { id: 'kissing_closed_eyes', char: '😚', desc: '闭眼亲亲' },
    { id: 'yum', char: '😋', desc: '好吃' },
    { id: 'stuck_out_tongue', char: '😛', desc: '吐舌' },
    { id: 'stuck_out_tongue_winking_eye', char: '😜', desc: '眨眼吐舌' },
    { id: 'money_mouth', char: '🤑', desc: '金钱嘴' },
    { id: 'hugging', char: '🤗', desc: '抱抱' },
    { id: 'sunglasses', char: '😎', desc: '酷' },
    { id: 'clown', char: '🤡', desc: '小丑脸' },
    { id: 'cowboy', char: '🤠', desc: '牛仔' },
    { id: 'imp', char: '👿', desc: '生气的恶魔' }
  ],
  gestures: [
    { id: 'wave', char: '👋', desc: '挥手' },
    { id: 'raised_back_of_hand', char: '🤚', desc: '立起的手背' },
    { id: 'raised_hand', char: '✋', desc: '举起手' },
    { id: 'vulcan_salute', char: '🖖', desc: '瓦肯举手礼' },
    { id: 'ok_hand', char: '👌', desc: 'ok' },
    { id: 'thumbs_down', char: '👎', desc: '拇指向下' },
    { id: 'middle_finger', char: '🖕', desc: '中指' },
    { id: 'victory', char: '✌️', desc: '胜利' },
    { id: 'crossed_fingers', char: '🤞', desc: '交叉手指' },
    { id: 'love_you_gesture', char: '🤟', desc: '爱你手势' },
    { id: 'metal', char: '🤘', desc: '摇滚' },
    { id: 'call_me', char: '🤙', desc: '打电话' },
    { id: 'point_left', char: '👈', desc: '指向左' },
    { id: 'point_right', char: '👉', desc: '指向右' },
    { id: 'point_up_2', char: '👆', desc: '指向上' },
    { id: 'middle_finger', char: '🖕', desc: '中指' },
    { id: 'point_down', char: '👇', desc: '指向下' },
    { id: 'point_up', char: '☝️', desc: '向上指' }
  ],
  animals: [
    { id: 'dog', char: '🐶', desc: '狗' },
    { id: 'cat', char: '🐱', desc: '猫' },
    { id: 'monkey_face', char: '🐵', desc: '猴脸' },
    { id: 'see_no_evil', char: '🙈', desc: '非礼勿视' },
    { id: 'hear_no_evil', char: '🙉', desc: '非礼勿听' },
    { id: 'speak_no_evil', char: '🙊', desc: '非礼勿言' }
  ],
  emotions: [
    { id: 'confused', char: '😕', desc: '困扰' },
    { id: 'thinking', char: '🤔', desc: '思考' },
    { id: 'frowning_face', char: '☹️', desc: '不满' },
    { id: 'confounded', char: '😖', desc: '困惑' },
    { id: 'weary', char: '😩', desc: '累死了' },
    { id: 'pleading_face', char: '🥺', desc: '恳求' },
    { id: 'cry', char: '😢', desc: '哭' },
    { id: 'sob', char: '😭', desc: '大哭' },
    { id: 'triumph', char: '😤', desc: '傲慢' },
    { id: 'angry', char: '😠', desc: '生气' },
    { id: 'face_with_symbols_on_mouth', char: '🤬', desc: '嘴上有符号的脸' },
    { id: 'flushed', char: '😳', desc: '脸红' },
    { id: 'disappointed', char: '😞', desc: '失望' },
    { id: 'worried', char: '😟', desc: '担心' },
    { id: 'expressionless', char: '😑', desc: '面无表情' },
    { id: 'no_mouth', char: '😶', desc: '没有嘴' },
    { id: 'grimacing', char: '😬', desc: '龇牙咧嘴' },
    { id: 'rolling_eyes', char: '🙄', desc: '翻白眼' },
    { id: 'hushed', char: '😯', desc: '缄默' },
    { id: 'frowning', char: '😦', desc: '皱眉' },
    { id: 'anguished', char: '😧', desc: '痛苦' },
    { id: 'open_mouth', char: '😮', desc: '吃惊' },
    { id: 'sleeping', char: '😴', desc: '睡觉' },
    { id: 'drooling_face', char: '🤤', desc: '流口水' },
    { id: 'sleepy', char: '😪', desc: '困' },
    { id: 'dizzy_face', char: '😵', desc: '晕' },
    { id: 'zipper_mouth', char: '🤐', desc: '拉链嘴' },
    { id: 'nauseated_face', char: '🤢', desc: '恶心' },
    { id: 'sneezing_face', char: '🤧', desc: '打喷嚏' },
    { id: 'mask', char: '😷', desc: '戴口罩' },
    { id: 'face_with_thermometer', char: '🤒', desc: '发烧' },
    { id: 'face_with_head_bandage', char: '🤕', desc: '受伤' },
    { id: 'woozy_face', char: '🥴', desc: '眩晕' },
    { id: 'lying_face', char: '🤥', desc: '说谎' },
    { id: 'sunglasses', char: '😎', desc: '戴墨镜' },
    { id: 'star_struck', char: '🤩', desc: '星星眼' },
    { id: 'partying_face', char: '🥳', desc: '派对脸' },
    { id: 'shushing_face', char: '🤫', desc: '嘘' },
    { id: 'face_with_hand_over_mouth', char: '🤭', desc: '捂嘴' },
    { id: 'face_vomiting', char: '🤮', desc: '呕吐' },
    { id: 'exploding_head', char: '🤯', desc: '爆炸头' },
    { id: 'hot_face', char: '🥵', desc: '脸发烧' },
    { id: 'cold_face', char: '🥶', desc: '冷脸' },
    { id: 'zany_face', char: '🤪', desc: '搞怪' },
    { id: 'money_mouth_face', char: '🤑', desc: '钱嘴' },
    { id: 'smiling_imp', char: '😈', desc: '恶魔微笑' },
    { id: 'imp', char: '👿', desc: '愤怒的小鬼' },
    { id: 'skull', char: '💀', desc: '头骨' },
    { id: 'skull_and_crossbones', char: '☠️', desc: '骷髅' },
    { id: 'hankey', char: '💩', desc: '大便' }
  ]
}

export default emojiData
